### ISSUE TITLE
Add Vagrant support so that developers can work locally

### ISSUE THREAD

**Issue by huodahaha** [nyu-devops-customers/customers#1]
**As a** developer
**I need** a way to work locally with Vagrant
**So that** I can be independent of any cloud services

**Assumptions:** 
* Use Vagrant and VirtualBox to build a local dev environment
* Python will be used for development

**Acceptance Criteria:**
When I issue `git clone` on the project
Add I change into the project folder
And I issue `vagrant up`
Then I should have a complete development environment on my workstation

**Comment by nerokapa** [comment]
Could you please rename the VM to be TeamAlpha.
